# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/2.8.12.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/2.8.12.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/local/Cellar/cmake/2.8.12.1/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/jsvana/Projects/project-yet-unnamed

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/jsvana/Projects/project-yet-unnamed

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/2.8.12.1/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/2.8.12.1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jsvana/Projects/project-yet-unnamed/CMakeFiles /Users/jsvana/Projects/project-yet-unnamed/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/jsvana/Projects/project-yet-unnamed/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bbs-client

# Build rule for target.
bbs-client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bbs-client
.PHONY : bbs-client

# fast build rule for target.
bbs-client/fast:
	$(MAKE) -f CMakeFiles/bbs-client.dir/build.make CMakeFiles/bbs-client.dir/build
.PHONY : bbs-client/fast

#=============================================================================
# Target rules for targets named bbs-server

# Build rule for target.
bbs-server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bbs-server
.PHONY : bbs-server

# fast build rule for target.
bbs-server/fast:
	$(MAKE) -f CMakeFiles/bbs-server.dir/build.make CMakeFiles/bbs-server.dir/build
.PHONY : bbs-server/fast

#=============================================================================
# Target rules for targets named seed

# Build rule for target.
seed: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 seed
.PHONY : seed

# fast build rule for target.
seed/fast:
	$(MAKE) -f CMakeFiles/seed.dir/build.make CMakeFiles/seed.dir/build
.PHONY : seed/fast

src/bbs_mysql.o: src/bbs_mysql.c.o
.PHONY : src/bbs_mysql.o

# target to build an object file
src/bbs_mysql.c.o:
	$(MAKE) -f CMakeFiles/bbs-server.dir/build.make CMakeFiles/bbs-server.dir/src/bbs_mysql.c.o
	$(MAKE) -f CMakeFiles/seed.dir/build.make CMakeFiles/seed.dir/src/bbs_mysql.c.o
.PHONY : src/bbs_mysql.c.o

src/bbs_mysql.i: src/bbs_mysql.c.i
.PHONY : src/bbs_mysql.i

# target to preprocess a source file
src/bbs_mysql.c.i:
	$(MAKE) -f CMakeFiles/bbs-server.dir/build.make CMakeFiles/bbs-server.dir/src/bbs_mysql.c.i
	$(MAKE) -f CMakeFiles/seed.dir/build.make CMakeFiles/seed.dir/src/bbs_mysql.c.i
.PHONY : src/bbs_mysql.c.i

src/bbs_mysql.s: src/bbs_mysql.c.s
.PHONY : src/bbs_mysql.s

# target to generate assembly for a file
src/bbs_mysql.c.s:
	$(MAKE) -f CMakeFiles/bbs-server.dir/build.make CMakeFiles/bbs-server.dir/src/bbs_mysql.c.s
	$(MAKE) -f CMakeFiles/seed.dir/build.make CMakeFiles/seed.dir/src/bbs_mysql.c.s
.PHONY : src/bbs_mysql.c.s

src/client_main.o: src/client_main.c.o
.PHONY : src/client_main.o

# target to build an object file
src/client_main.c.o:
	$(MAKE) -f CMakeFiles/bbs-client.dir/build.make CMakeFiles/bbs-client.dir/src/client_main.c.o
.PHONY : src/client_main.c.o

src/client_main.i: src/client_main.c.i
.PHONY : src/client_main.i

# target to preprocess a source file
src/client_main.c.i:
	$(MAKE) -f CMakeFiles/bbs-client.dir/build.make CMakeFiles/bbs-client.dir/src/client_main.c.i
.PHONY : src/client_main.c.i

src/client_main.s: src/client_main.c.s
.PHONY : src/client_main.s

# target to generate assembly for a file
src/client_main.c.s:
	$(MAKE) -f CMakeFiles/bbs-client.dir/build.make CMakeFiles/bbs-client.dir/src/client_main.c.s
.PHONY : src/client_main.c.s

src/common.o: src/common.c.o
.PHONY : src/common.o

# target to build an object file
src/common.c.o:
	$(MAKE) -f CMakeFiles/bbs-client.dir/build.make CMakeFiles/bbs-client.dir/src/common.c.o
	$(MAKE) -f CMakeFiles/bbs-server.dir/build.make CMakeFiles/bbs-server.dir/src/common.c.o
	$(MAKE) -f CMakeFiles/seed.dir/build.make CMakeFiles/seed.dir/src/common.c.o
.PHONY : src/common.c.o

src/common.i: src/common.c.i
.PHONY : src/common.i

# target to preprocess a source file
src/common.c.i:
	$(MAKE) -f CMakeFiles/bbs-client.dir/build.make CMakeFiles/bbs-client.dir/src/common.c.i
	$(MAKE) -f CMakeFiles/bbs-server.dir/build.make CMakeFiles/bbs-server.dir/src/common.c.i
	$(MAKE) -f CMakeFiles/seed.dir/build.make CMakeFiles/seed.dir/src/common.c.i
.PHONY : src/common.c.i

src/common.s: src/common.c.s
.PHONY : src/common.s

# target to generate assembly for a file
src/common.c.s:
	$(MAKE) -f CMakeFiles/bbs-client.dir/build.make CMakeFiles/bbs-client.dir/src/common.c.s
	$(MAKE) -f CMakeFiles/bbs-server.dir/build.make CMakeFiles/bbs-server.dir/src/common.c.s
	$(MAKE) -f CMakeFiles/seed.dir/build.make CMakeFiles/seed.dir/src/common.c.s
.PHONY : src/common.c.s

src/seed.o: src/seed.c.o
.PHONY : src/seed.o

# target to build an object file
src/seed.c.o:
	$(MAKE) -f CMakeFiles/seed.dir/build.make CMakeFiles/seed.dir/src/seed.c.o
.PHONY : src/seed.c.o

src/seed.i: src/seed.c.i
.PHONY : src/seed.i

# target to preprocess a source file
src/seed.c.i:
	$(MAKE) -f CMakeFiles/seed.dir/build.make CMakeFiles/seed.dir/src/seed.c.i
.PHONY : src/seed.c.i

src/seed.s: src/seed.c.s
.PHONY : src/seed.s

# target to generate assembly for a file
src/seed.c.s:
	$(MAKE) -f CMakeFiles/seed.dir/build.make CMakeFiles/seed.dir/src/seed.c.s
.PHONY : src/seed.c.s

src/server_main.o: src/server_main.c.o
.PHONY : src/server_main.o

# target to build an object file
src/server_main.c.o:
	$(MAKE) -f CMakeFiles/bbs-server.dir/build.make CMakeFiles/bbs-server.dir/src/server_main.c.o
.PHONY : src/server_main.c.o

src/server_main.i: src/server_main.c.i
.PHONY : src/server_main.i

# target to preprocess a source file
src/server_main.c.i:
	$(MAKE) -f CMakeFiles/bbs-server.dir/build.make CMakeFiles/bbs-server.dir/src/server_main.c.i
.PHONY : src/server_main.c.i

src/server_main.s: src/server_main.c.s
.PHONY : src/server_main.s

# target to generate assembly for a file
src/server_main.c.s:
	$(MAKE) -f CMakeFiles/bbs-server.dir/build.make CMakeFiles/bbs-server.dir/src/server_main.c.s
.PHONY : src/server_main.c.s

src/utils/mqueue.o: src/utils/mqueue.c.o
.PHONY : src/utils/mqueue.o

# target to build an object file
src/utils/mqueue.c.o:
	$(MAKE) -f CMakeFiles/bbs-client.dir/build.make CMakeFiles/bbs-client.dir/src/utils/mqueue.c.o
.PHONY : src/utils/mqueue.c.o

src/utils/mqueue.i: src/utils/mqueue.c.i
.PHONY : src/utils/mqueue.i

# target to preprocess a source file
src/utils/mqueue.c.i:
	$(MAKE) -f CMakeFiles/bbs-client.dir/build.make CMakeFiles/bbs-client.dir/src/utils/mqueue.c.i
.PHONY : src/utils/mqueue.c.i

src/utils/mqueue.s: src/utils/mqueue.c.s
.PHONY : src/utils/mqueue.s

# target to generate assembly for a file
src/utils/mqueue.c.s:
	$(MAKE) -f CMakeFiles/bbs-client.dir/build.make CMakeFiles/bbs-client.dir/src/utils/mqueue.c.s
.PHONY : src/utils/mqueue.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... bbs-client"
	@echo "... bbs-server"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... seed"
	@echo "... src/bbs_mysql.o"
	@echo "... src/bbs_mysql.i"
	@echo "... src/bbs_mysql.s"
	@echo "... src/client_main.o"
	@echo "... src/client_main.i"
	@echo "... src/client_main.s"
	@echo "... src/common.o"
	@echo "... src/common.i"
	@echo "... src/common.s"
	@echo "... src/seed.o"
	@echo "... src/seed.i"
	@echo "... src/seed.s"
	@echo "... src/server_main.o"
	@echo "... src/server_main.i"
	@echo "... src/server_main.s"
	@echo "... src/utils/mqueue.o"
	@echo "... src/utils/mqueue.i"
	@echo "... src/utils/mqueue.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

